import { Inter } from "next/font/google";
import "./globals.css";

import { faChartBar } from "@fortawesome/free-solid-svg-icons";
import { faUser } from "@fortawesome/free-solid-svg-icons";
import { faDiagramProject } from "@fortawesome/free-solid-svg-icons";
import { faBuildingColumns } from "@fortawesome/free-solid-svg-icons";

import SidebarListItem from "./Components/SidebarListItem";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Dashboard",
  description: "Generated by create next app By Hamada-99-77",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main
          className="flex min-h-screen bg-gray-100" /*main: contains Sidebar and Content*/
        >
          <div className="bg-white p-5 relative" /*Sidebar*/>
            <h3 className="mb-6 text-green-800 font-extrabold text-lg text-center">
              Next-JP-D
            </h3>

            <ul className="space-y-6">
              <SidebarListItem linkTo="/" icon={faChartBar} name="JP-D" />

              <SidebarListItem linkTo="/profile" icon={faUser} name="Profile" />

              <SidebarListItem
                linkTo="/projects"
                icon={faDiagramProject}
                name="Projects"
              />

              <SidebarListItem
                linkTo="/tAndc"
                icon={faBuildingColumns}
                name="T &amp; C"
              />
            </ul>
          </div>

          <div className="" /*Content*/>{children}</div>
        </main>
      </body>
    </html>
  );
}
