import { Inter } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/SidebarComponents/Sidebar";
import Header from "@/components/Header";
import PagesHolder from "@/components/PagesHolder";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hotel",
  description: "Generated by create next app By Hamada-99-77",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main
          className="h-screen grid grid-cols-[5rem,1fr] md:grid-cols-[10rem,1fr] grid-rows-[auto,1fr] bg-gray-400" /*main: contains Header, Sidebar and Content*/
        >
          <Header />
          <Sidebar />
          <PagesHolder>{children}</PagesHolder>
        </main>
      </body>
    </html>
  );
}
